name: Deploy Next.js to Azure

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Locate .next directory
        run: find . -name ".next" -type d  # Finds the exact path of .next

      - name: List files for debugging
        run: ls -a  # Lists all files, including hidden ones, to confirm .next is present

      - name: Set permissions on .next
        run: chmod -R 755 .next  # Ensures the .next folder is accessible

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: next-build
          path: ./.next  # Adjust the path if the find command shows a different location
